services:
  bot:
    image: ghcr.io/mai0313/llm_discord_bot:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: bot
    command:
      - python
      - ./main.py
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: always
    pull_policy: if_not_present
