services:
  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: bot
    command:
      - python
      - ./main.py
    volumes:
      - ./logs:/app/logs
    restart: always
    pull_policy: if_not_present
