services:
  bot:
    image: ghcr.io/mai0313/llm_discord_bot:latest
    build:
      context: .
      target: prod
      dockerfile: ./docker/Dockerfile
    command:
      - python
      - ./main.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always
    pull_policy: always

  postgresql:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    restart: always
    pull_policy: always

  redis:
    image: redis:7.2.5-alpine
    command:
      - redis-server
    volumes:
      - ./data/redis:/var/lib/redis
    restart: always
    pull_policy: always
